# Generated by Django 5.2.14 on 2026-06-25 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LDAPUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid_number', models.PositiveIntegerField(help_text='POSIX uidNumber. Must be unique across all users.', unique=True)),
                ('gid_number', models.PositiveIntegerField(help_text='Primary POSIX gidNumber.')),
                ('home_directory', models.CharField(blank=True, help_text='POSIX home directory path, e.g. /nfs/home/jmill165', max_length=512)),
                ('login_shell', models.CharField(default='/bin/bash', help_text='POSIX login shell.', max_length=255)),
                ('gecos', models.CharField(blank=True, help_text="GECOS field. Auto-generated from user's name if left blank.", max_length=512)),
                ('shadow_last_change', models.IntegerField(default=0, help_text='Days since epoch of last password change (shadowLastChange).')),
                ('shadow_max', models.IntegerField(default=99999, help_text='Max days before password must be changed (shadowMax).')),
                ('shadow_warning', models.IntegerField(default=7, help_text='Days before expiry to warn user (shadowWarning).')),
                ('ldap_password', models.CharField(blank=True, help_text='LDAP userPassword (pre-hashed, e.g. {SSHA384}...). This is NOT the Django login password.', max_length=1024)),
                ('hosts', models.ManyToManyField(blank=True, help_text='LDAP host entries this user is authorized for.', to='ldap_user_profile.ldaphost')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ldapuserprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LDAP User Profile',
                'verbose_name_plural': 'LDAP User Profiles',
            },
        ),
    ]
